using System;
using System.Collections.Generic;

namespace PowerBiometricsAPI.Data.Models
{
    public partial class InventoryItems
    {
        public string CompanyId { get; set; }
        public string DivisionId { get; set; }
        public string DepartmentId { get; set; }
        public string ItemId { get; set; }
        public bool? IsActive { get; set; }
        public string ItemTypeId { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string ItemLongDescription { get; set; }
        public string ItemCategoryId { get; set; }
        public string ItemFamilyId { get; set; }
        public string SalesDescription { get; set; }
        public string PurchaseDescription { get; set; }
        public string PictureUrl { get; set; }
        public string LargePictureUrl { get; set; }
        public double? ItemWeight { get; set; }
        public double? ItemWeightMetric { get; set; }
        public int? ItemShipWeight { get; set; }
        public string ItemUpccode { get; set; }
        public string ItemEpccode { get; set; }
        public string ItemRfid { get; set; }
        public string ItemSize { get; set; }
        public string ItemSizeCmm { get; set; }
        public string ItemDimentions { get; set; }
        public string ItemDimentionsCmm { get; set; }
        public string ItemColor { get; set; }
        public string ItemNrfcolor { get; set; }
        public string ItemStyle { get; set; }
        public string ItemNrfstyle { get; set; }
        public string ItemCareInstructions { get; set; }
        public string ItemDefaultWarehouse { get; set; }
        public string ItemDefaultWarehouseBin { get; set; }
        public string ItemLocationX { get; set; }
        public string ItemLocationY { get; set; }
        public string ItemLocationZ { get; set; }
        public string DownloadLocation { get; set; }
        public string DownloadPassword { get; set; }
        public string ItemUom { get; set; }
        public string GlitemSalesAccount { get; set; }
        public string GlitemCogsaccount { get; set; }
        public string GlitemInventoryAccount { get; set; }
        public string PackId { get; set; }
        public string CurrencyId { get; set; }
        public double? CurrencyExchangeRate { get; set; }
        public decimal? Price { get; set; }
        public string ItemPricingCode { get; set; }
        public string PricingMethods { get; set; }
        public bool? Taxable { get; set; }
        public string VendorId { get; set; }
        public string LeadTime { get; set; }
        public string LeadTimeUnit { get; set; }
        public double? ReOrderLevel { get; set; }
        public double? ReOrderQty { get; set; }
        public int? BuildTime { get; set; }
        public string BuildTimeUnit { get; set; }
        public int? UseageRate { get; set; }
        public string UseageRateUnit { get; set; }
        public int? SalesForecast { get; set; }
        public string SalesForecastUnit { get; set; }
        public int? CalculatedCover { get; set; }
        public string CalculatedCoverUnits { get; set; }
        public bool? IsAssembly { get; set; }
        public string ItemAssembly { get; set; }
        public decimal? Lifo { get; set; }
        public decimal? Lifovalue { get; set; }
        public decimal? Lifocost { get; set; }
        public decimal? Average { get; set; }
        public decimal? AverageValue { get; set; }
        public decimal? AverageCost { get; set; }
        public decimal? Fifo { get; set; }
        public decimal? Fifovalue { get; set; }
        public decimal? Fifocost { get; set; }
        public decimal? Expected { get; set; }
        public decimal? ExpectedValue { get; set; }
        public decimal? ExpectedCost { get; set; }
        public decimal? Landed { get; set; }
        public decimal? LandedValue { get; set; }
        public decimal? LandedCost { get; set; }
        public decimal? Other { get; set; }
        public decimal? OtherValue { get; set; }
        public decimal? OtherCost { get; set; }
        public bool? Commissionable { get; set; }
        public short? CommissionType { get; set; }
        public double? CommissionPerc { get; set; }
        public bool? Approved { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public string EnteredBy { get; set; }
        public string TaxGroupId { get; set; }
        public double? TaxPercent { get; set; }
        public string LockedBy { get; set; }
        public DateTime? LockTs { get; set; }
        public bool? IsSerialLotItem { get; set; }
        public bool? IsWarrantyItem { get; set; }
        public int? WarrantyPeriod { get; set; }
        public double? MinimumQty { get; set; }
        public DateTime? LastEditDate { get; set; }
        public DateTime? CreationDate { get; set; }
        public string GlitemFreightAccount { get; set; }
        public string GlitemHandlingAccount { get; set; }
        public bool? AllowPurchaseTrans { get; set; }
        public bool? AllowSalesTrans { get; set; }
        public bool? AllowInventoryTrans { get; set; }
        public double? ToleranceLevel { get; set; }
        public byte[] Picture { get; set; }
        public string BranchCode { get; set; }
    }
}
