using System;
using System.Collections.Generic;

namespace PowerBiometricsAPI.Data.Models
{
    public partial class PurchaseReceiptHeaderHistory
    {
        public string CompanyId { get; set; }
        public string DivisionId { get; set; }
        public string DepartmentId { get; set; }
        public string PurchaseNumber { get; set; }
        public string TransactionTypeId { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public DateTime? PurchaseDueDate { get; set; }
        public DateTime? PurchaseShipDate { get; set; }
        public DateTime? PurchaseCancelDate { get; set; }
        public DateTime? PurchaseDateRequested { get; set; }
        public DateTime? SystemDate { get; set; }
        public bool? Memorize { get; set; }
        public string OrderNumber { get; set; }
        public string VendorInvoiceNumber { get; set; }
        public string OrderedBy { get; set; }
        public string TaxExemptId { get; set; }
        public string TaxGroupId { get; set; }
        public string VendorId { get; set; }
        public string TermsId { get; set; }
        public string CurrencyId { get; set; }
        public double? CurrencyExchangeRate { get; set; }
        public decimal? Subtotal { get; set; }
        public double? DiscountPers { get; set; }
        public decimal? DiscountAmount { get; set; }
        public double? TaxPercent { get; set; }
        public decimal? TaxAmount { get; set; }
        public decimal? TaxableSubTotal { get; set; }
        public decimal? Freight { get; set; }
        public bool? TaxFreight { get; set; }
        public decimal? Handling { get; set; }
        public decimal? Advertising { get; set; }
        public decimal? Total { get; set; }
        public bool? ShipToWarehouse { get; set; }
        public string WarehouseId { get; set; }
        public string ShipMethodId { get; set; }
        public string ShippingName { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingAddress3 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public string ShippingCountry { get; set; }
        public bool? Paid { get; set; }
        public string PaymentId { get; set; }
        public string PaymentMethodId { get; set; }
        public DateTime? PaymentDate { get; set; }
        public string GlpurchaseAccount { get; set; }
        public decimal? AmountPaid { get; set; }
        public decimal? BalanceDue { get; set; }
        public decimal? UndistributedAmount { get; set; }
        public string CheckNumber { get; set; }
        public DateTime? CheckDate { get; set; }
        public DateTime? PaidDate { get; set; }
        public string CreditCardTypeId { get; set; }
        public string CreditCardName { get; set; }
        public string CreditCardNumber { get; set; }
        public DateTime? CreditCardExpDate { get; set; }
        public string CreditCardCsvnumber { get; set; }
        public string CreditCardBillToZip { get; set; }
        public string CreditCardValidationCode { get; set; }
        public string CreditCardApprovalNumber { get; set; }
        public bool? Approved { get; set; }
        public string ApprovedBy { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public bool? Printed { get; set; }
        public DateTime? PrintedDate { get; set; }
        public bool? Shipped { get; set; }
        public DateTime? ShipDate { get; set; }
        public string TrackingNumber { get; set; }
        public bool? Received { get; set; }
        public DateTime? ReceivedDate { get; set; }
        public string RecivingNumber { get; set; }
        public bool? Posted { get; set; }
        public DateTime? PostedDate { get; set; }
        public bool? CommissionPaid { get; set; }
        public bool? CommissionSelectToPay { get; set; }
        public string OriginalPurchaseNumber { get; set; }
        public DateTime? OriginalPurchaseDate { get; set; }
        public string HeaderMemo1 { get; set; }
        public string HeaderMemo2 { get; set; }
        public string HeaderMemo3 { get; set; }
        public string HeaderMemo4 { get; set; }
        public string HeaderMemo5 { get; set; }
        public string HeaderMemo6 { get; set; }
        public string HeaderMemo7 { get; set; }
        public string HeaderMemo8 { get; set; }
        public string HeaderMemo9 { get; set; }
        public string EnteredBy { get; set; }
        public string Signature { get; set; }
        public string SignaturePassword { get; set; }
        public string SupervisorSignature { get; set; }
        public string SupervisorPassword { get; set; }
        public string ManagerSignature { get; set; }
        public string ManagerPassword { get; set; }
        public string LockedBy { get; set; }
        public DateTime? LockTs { get; set; }
        public string PurchaseContractNumber { get; set; }
        public string BankId { get; set; }
        public decimal? TotalAdditionalCost { get; set; }
        public string BranchCode { get; set; }
    }
}
